// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StickerResources.proto

package su.sres.signalservice.internal.sticker;

public final class StickerProtos {
  private StickerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.Pack)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string title = 1;</code>
     * @return Whether the title field is set.
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string author = 2;</code>
     * @return Whether the author field is set.
     */
    boolean hasAuthor();
    /**
     * <code>optional string author = 2;</code>
     * @return The author.
     */
    java.lang.String getAuthor();
    /**
     * <code>optional string author = 2;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     * @return Whether the cover field is set.
     */
    boolean hasCover();
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     * @return The cover.
     */
    su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getCover();

    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    java.util.List<su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> 
        getStickersList();
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getStickers(int index);
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    int getStickersCount();
  }
  /**
   * Protobuf type {@code signalservice.Pack}
   */
  public  static final class Pack extends
      com.google.protobuf.GeneratedMessageLite<
          Pack, Pack.Builder> implements
      // @@protoc_insertion_point(message_implements:signalservice.Pack)
      PackOrBuilder {
    private Pack() {
      title_ = "";
      author_ = "";
      stickers_ = emptyProtobufList();
    }
    public interface StickerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:signalservice.Pack.Sticker)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional uint32 id = 1;</code>
       * @return Whether the id field is set.
       */
      boolean hasId();
      /**
       * <code>optional uint32 id = 1;</code>
       * @return The id.
       */
      int getId();

      /**
       * <code>optional string emoji = 2;</code>
       * @return Whether the emoji field is set.
       */
      boolean hasEmoji();
      /**
       * <code>optional string emoji = 2;</code>
       * @return The emoji.
       */
      java.lang.String getEmoji();
      /**
       * <code>optional string emoji = 2;</code>
       * @return The bytes for emoji.
       */
      com.google.protobuf.ByteString
          getEmojiBytes();
    }
    /**
     * Protobuf type {@code signalservice.Pack.Sticker}
     */
    public  static final class Sticker extends
        com.google.protobuf.GeneratedMessageLite<
            Sticker, Sticker.Builder> implements
        // @@protoc_insertion_point(message_implements:signalservice.Pack.Sticker)
        StickerOrBuilder {
      private Sticker() {
        emoji_ = "";
      }
      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>optional uint32 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       * @param value The id to set.
       */
      private void setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      private void clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
      }

      public static final int EMOJI_FIELD_NUMBER = 2;
      private java.lang.String emoji_;
      /**
       * <code>optional string emoji = 2;</code>
       * @return Whether the emoji field is set.
       */
      @java.lang.Override
      public boolean hasEmoji() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string emoji = 2;</code>
       * @return The emoji.
       */
      @java.lang.Override
      public java.lang.String getEmoji() {
        return emoji_;
      }
      /**
       * <code>optional string emoji = 2;</code>
       * @return The bytes for emoji.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmojiBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(emoji_);
      }
      /**
       * <code>optional string emoji = 2;</code>
       * @param value The emoji to set.
       */
      private void setEmoji(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        emoji_ = value;
      }
      /**
       * <code>optional string emoji = 2;</code>
       */
      private void clearEmoji() {
        bitField0_ = (bitField0_ & ~0x00000002);
        emoji_ = getDefaultInstance().getEmoji();
      }
      /**
       * <code>optional string emoji = 2;</code>
       * @param value The bytes for emoji to set.
       */
      private void setEmojiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        emoji_ = value.toStringUtf8();
      }

      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code signalservice.Pack.Sticker}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker, Builder> implements
          // @@protoc_insertion_point(builder_implements:signalservice.Pack.Sticker)
          su.sres.signalservice.internal.sticker.StickerProtos.Pack.StickerOrBuilder {
        // Construct using su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional uint32 id = 1;</code>
         * @return Whether the id field is set.
         */
        @java.lang.Override
        public boolean hasId() {
          return instance.hasId();
        }
        /**
         * <code>optional uint32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
          return instance.getId();
        }
        /**
         * <code>optional uint32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
          copyOnWrite();
          instance.setId(value);
          return this;
        }
        /**
         * <code>optional uint32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          copyOnWrite();
          instance.clearId();
          return this;
        }

        /**
         * <code>optional string emoji = 2;</code>
         * @return Whether the emoji field is set.
         */
        @java.lang.Override
        public boolean hasEmoji() {
          return instance.hasEmoji();
        }
        /**
         * <code>optional string emoji = 2;</code>
         * @return The emoji.
         */
        @java.lang.Override
        public java.lang.String getEmoji() {
          return instance.getEmoji();
        }
        /**
         * <code>optional string emoji = 2;</code>
         * @return The bytes for emoji.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getEmojiBytes() {
          return instance.getEmojiBytes();
        }
        /**
         * <code>optional string emoji = 2;</code>
         * @param value The emoji to set.
         * @return This builder for chaining.
         */
        public Builder setEmoji(
            java.lang.String value) {
          copyOnWrite();
          instance.setEmoji(value);
          return this;
        }
        /**
         * <code>optional string emoji = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearEmoji() {
          copyOnWrite();
          instance.clearEmoji();
          return this;
        }
        /**
         * <code>optional string emoji = 2;</code>
         * @param value The bytes for emoji to set.
         * @return This builder for chaining.
         */
        public Builder setEmojiBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setEmojiBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:signalservice.Pack.Sticker)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "bitField0_",
                "id_",
                "emoji_",
              };
              java.lang.String info =
                  "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0000\u0002" +
                  "\b\u0001";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> parser = PARSER;
            if (parser == null) {
              synchronized (su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:signalservice.Pack.Sticker)
      private static final su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker DEFAULT_INSTANCE;
      static {
        Sticker defaultInstance = new Sticker();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          Sticker.class, defaultInstance);
      }

      public static su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Sticker> PARSER;

      public static com.google.protobuf.Parser<Sticker> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private java.lang.String title_;
    /**
     * <code>optional string title = 1;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The title to set.
     */
    private void setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      title_ = value;
    }
    /**
     * <code>optional string title = 1;</code>
     */
    private void clearTitle() {
      bitField0_ = (bitField0_ & ~0x00000001);
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      title_ = value.toStringUtf8();
    }

    public static final int AUTHOR_FIELD_NUMBER = 2;
    private java.lang.String author_;
    /**
     * <code>optional string author = 2;</code>
     * @return Whether the author field is set.
     */
    @java.lang.Override
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string author = 2;</code>
     * @return The author.
     */
    @java.lang.Override
    public java.lang.String getAuthor() {
      return author_;
    }
    /**
     * <code>optional string author = 2;</code>
     * @return The bytes for author.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(author_);
    }
    /**
     * <code>optional string author = 2;</code>
     * @param value The author to set.
     */
    private void setAuthor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      author_ = value;
    }
    /**
     * <code>optional string author = 2;</code>
     */
    private void clearAuthor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      author_ = getDefaultInstance().getAuthor();
    }
    /**
     * <code>optional string author = 2;</code>
     * @param value The bytes for author to set.
     */
    private void setAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      author_ = value.toStringUtf8();
    }

    public static final int COVER_FIELD_NUMBER = 3;
    private su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker cover_;
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     */
    @java.lang.Override
    public boolean hasCover() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     */
    @java.lang.Override
    public su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getCover() {
      return cover_ == null ? su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.getDefaultInstance() : cover_;
    }
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     */
    private void setCover(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
      if (value == null) {
        throw new NullPointerException();
      }
      cover_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     */
    private void setCover(
        su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
      cover_ = builderForValue.build();
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCover(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (cover_ != null &&
          cover_ != su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.getDefaultInstance()) {
        cover_ =
          su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.newBuilder(cover_).mergeFrom(value).buildPartial();
      } else {
        cover_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
     */
    private void clearCover() {  cover_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static final int STICKERS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> stickers_;
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    @java.lang.Override
    public java.util.List<su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> getStickersList() {
      return stickers_;
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    public java.util.List<? extends su.sres.signalservice.internal.sticker.StickerProtos.Pack.StickerOrBuilder> 
        getStickersOrBuilderList() {
      return stickers_;
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    @java.lang.Override
    public int getStickersCount() {
      return stickers_.size();
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    @java.lang.Override
    public su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getStickers(int index) {
      return stickers_.get(index);
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    public su.sres.signalservice.internal.sticker.StickerProtos.Pack.StickerOrBuilder getStickersOrBuilder(
        int index) {
      return stickers_.get(index);
    }
    private void ensureStickersIsMutable() {
      if (!stickers_.isModifiable()) {
        stickers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(stickers_);
       }
    }

    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void setStickers(
        int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureStickersIsMutable();
      stickers_.set(index, value);
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void setStickers(
        int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
      ensureStickersIsMutable();
      stickers_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void addStickers(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureStickersIsMutable();
      stickers_.add(value);
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void addStickers(
        int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureStickersIsMutable();
      stickers_.add(index, value);
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void addStickers(
        su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
      ensureStickersIsMutable();
      stickers_.add(builderForValue.build());
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void addStickers(
        int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
      ensureStickersIsMutable();
      stickers_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void addAllStickers(
        java.lang.Iterable<? extends su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> values) {
      ensureStickersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, stickers_);
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void clearStickers() {
      stickers_ = emptyProtobufList();
    }
    /**
     * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
     */
    private void removeStickers(int index) {
      ensureStickersIsMutable();
      stickers_.remove(index);
    }

    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(su.sres.signalservice.internal.sticker.StickerProtos.Pack prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code signalservice.Pack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          su.sres.signalservice.internal.sticker.StickerProtos.Pack, Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.Pack)
        su.sres.signalservice.internal.sticker.StickerProtos.PackOrBuilder {
      // Construct using su.sres.signalservice.internal.sticker.StickerProtos.Pack.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string title = 1;</code>
       * @return Whether the title field is set.
       */
      @java.lang.Override
      public boolean hasTitle() {
        return instance.hasTitle();
      }
      /**
       * <code>optional string title = 1;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>optional string title = 1;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>optional string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>optional string author = 2;</code>
       * @return Whether the author field is set.
       */
      @java.lang.Override
      public boolean hasAuthor() {
        return instance.hasAuthor();
      }
      /**
       * <code>optional string author = 2;</code>
       * @return The author.
       */
      @java.lang.Override
      public java.lang.String getAuthor() {
        return instance.getAuthor();
      }
      /**
       * <code>optional string author = 2;</code>
       * @return The bytes for author.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        return instance.getAuthorBytes();
      }
      /**
       * <code>optional string author = 2;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          java.lang.String value) {
        copyOnWrite();
        instance.setAuthor(value);
        return this;
      }
      /**
       * <code>optional string author = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        copyOnWrite();
        instance.clearAuthor();
        return this;
      }
      /**
       * <code>optional string author = 2;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAuthorBytes(value);
        return this;
      }

      /**
       * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
       */
      @java.lang.Override
      public boolean hasCover() {
        return instance.hasCover();
      }
      /**
       * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
       */
      @java.lang.Override
      public su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getCover() {
        return instance.getCover();
      }
      /**
       * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
       */
      public Builder setCover(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
        copyOnWrite();
        instance.setCover(value);
        return this;
        }
      /**
       * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
       */
      public Builder setCover(
          su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
        copyOnWrite();
        instance.setCover(builderForValue);
        return this;
      }
      /**
       * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
       */
      public Builder mergeCover(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
        copyOnWrite();
        instance.mergeCover(value);
        return this;
      }
      /**
       * <code>optional .signalservice.Pack.Sticker cover = 3;</code>
       */
      public Builder clearCover() {  copyOnWrite();
        instance.clearCover();
        return this;
      }

      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      @java.lang.Override
      public java.util.List<su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> getStickersList() {
        return java.util.Collections.unmodifiableList(
            instance.getStickersList());
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      @java.lang.Override
      public int getStickersCount() {
        return instance.getStickersCount();
      }/**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      @java.lang.Override
      public su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker getStickers(int index) {
        return instance.getStickers(index);
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder setStickers(
          int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
        copyOnWrite();
        instance.setStickers(index, value);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder setStickers(
          int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
        copyOnWrite();
        instance.setStickers(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder addStickers(su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
        copyOnWrite();
        instance.addStickers(value);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder addStickers(
          int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker value) {
        copyOnWrite();
        instance.addStickers(index, value);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder addStickers(
          su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
        copyOnWrite();
        instance.addStickers(builderForValue);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder addStickers(
          int index, su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.Builder builderForValue) {
        copyOnWrite();
        instance.addStickers(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder addAllStickers(
          java.lang.Iterable<? extends su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker> values) {
        copyOnWrite();
        instance.addAllStickers(values);
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder clearStickers() {
        copyOnWrite();
        instance.clearStickers();
        return this;
      }
      /**
       * <code>repeated .signalservice.Pack.Sticker stickers = 4;</code>
       */
      public Builder removeStickers(int index) {
        copyOnWrite();
        instance.removeStickers(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signalservice.Pack)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new su.sres.signalservice.internal.sticker.StickerProtos.Pack();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "title_",
              "author_",
              "cover_",
              "stickers_",
              su.sres.signalservice.internal.sticker.StickerProtos.Pack.Sticker.class,
            };
            java.lang.String info =
                "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0001\u0000\u0001\b\u0000\u0002" +
                "\b\u0001\u0003\t\u0002\u0004\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<su.sres.signalservice.internal.sticker.StickerProtos.Pack> parser = PARSER;
          if (parser == null) {
            synchronized (su.sres.signalservice.internal.sticker.StickerProtos.Pack.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<su.sres.signalservice.internal.sticker.StickerProtos.Pack>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:signalservice.Pack)
    private static final su.sres.signalservice.internal.sticker.StickerProtos.Pack DEFAULT_INSTANCE;
    static {
      Pack defaultInstance = new Pack();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Pack.class, defaultInstance);
    }

    public static su.sres.signalservice.internal.sticker.StickerProtos.Pack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Pack> PARSER;

    public static com.google.protobuf.Parser<Pack> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
