// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Provisioning.proto

package su.sres.signalservice.internal.push;

public final class ProvisioningProtos {
  private ProvisioningProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code signalservice.ProvisioningVersion}
   */
  public enum ProvisioningVersion
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>INITIAL = 0;</code>
     */
    INITIAL(0),
    /**
     * <code>TABLET_SUPPORT = 1;</code>
     */
    TABLET_SUPPORT(1),
    ;

    /**
     * <code>CURRENT = 1;</code>
     */
    public static final ProvisioningVersion CURRENT = TABLET_SUPPORT;
    /**
     * <code>INITIAL = 0;</code>
     */
    public static final int INITIAL_VALUE = 0;
    /**
     * <code>TABLET_SUPPORT = 1;</code>
     */
    public static final int TABLET_SUPPORT_VALUE = 1;
    /**
     * <code>CURRENT = 1;</code>
     */
    public static final int CURRENT_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProvisioningVersion valueOf(int value) {
      return forNumber(value);
    }

    public static ProvisioningVersion forNumber(int value) {
      switch (value) {
        case 0: return INITIAL;
        case 1: return TABLET_SUPPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProvisioningVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProvisioningVersion> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProvisioningVersion>() {
            @java.lang.Override
            public ProvisioningVersion findValueByNumber(int number) {
              return ProvisioningVersion.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ProvisioningVersionVerifier.INSTANCE;
    }

    private static final class ProvisioningVersionVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ProvisioningVersionVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ProvisioningVersion.forNumber(number) != null;
            }
          };

    private final int value;

    private ProvisioningVersion(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:signalservice.ProvisioningVersion)
  }

  public interface ProvisionEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisionEnvelope)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes publicKey = 1;</code>
     * @return Whether the publicKey field is set.
     */
    boolean hasPublicKey();
    /**
     * <code>optional bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code signalservice.ProvisionEnvelope}
   */
  public  static final class ProvisionEnvelope extends
      com.google.protobuf.GeneratedMessageLite<
          ProvisionEnvelope, ProvisionEnvelope.Builder> implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisionEnvelope)
      ProvisionEnvelopeOrBuilder {
    private ProvisionEnvelope() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>optional bytes publicKey = 1;</code>
     * @return Whether the publicKey field is set.
     */
    @java.lang.Override
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     * @param value The publicKey to set.
     */
    private void setPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      publicKey_ = value;
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    private void clearPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      publicKey_ = getDefaultInstance().getPublicKey();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     * @param value The body to set.
     */
    private void setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      body_ = value;
    }
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    private void clearBody() {
      bitField0_ = (bitField0_ & ~0x00000002);
      body_ = getDefaultInstance().getBody();
    }

    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code signalservice.ProvisionEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope, Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisionEnvelope)
        su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelopeOrBuilder {
      // Construct using su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes publicKey = 1;</code>
       * @return Whether the publicKey field is set.
       */
      @java.lang.Override
      public boolean hasPublicKey() {
        return instance.hasPublicKey();
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       * @return The publicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPublicKey() {
        return instance.getPublicKey();
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPublicKey(value);
        return this;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        copyOnWrite();
        instance.clearPublicKey();
        return this;
      }

      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       * @return Whether the body field is set.
       */
      @java.lang.Override
      public boolean hasBody() {
        return instance.hasBody();
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return instance.getBody();
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBody(value);
        return this;
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        copyOnWrite();
        instance.clearBody();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signalservice.ProvisionEnvelope)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "publicKey_",
              "body_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0000\u0002" +
                "\n\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope> parser = PARSER;
          if (parser == null) {
            synchronized (su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:signalservice.ProvisionEnvelope)
    private static final su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope DEFAULT_INSTANCE;
    static {
      ProvisionEnvelope defaultInstance = new ProvisionEnvelope();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ProvisionEnvelope.class, defaultInstance);
    }

    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ProvisionEnvelope> PARSER;

    public static com.google.protobuf.Parser<ProvisionEnvelope> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ProvisionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisionMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     * @return Whether the identityKeyPublic field is set.
     */
    boolean hasIdentityKeyPublic();
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     * @return The identityKeyPublic.
     */
    com.google.protobuf.ByteString getIdentityKeyPublic();

    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     * @return Whether the identityKeyPrivate field is set.
     */
    boolean hasIdentityKeyPrivate();
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     * @return The identityKeyPrivate.
     */
    com.google.protobuf.ByteString getIdentityKeyPrivate();

    /**
     * <code>optional string number = 3;</code>
     * @return Whether the number field is set.
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 3;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 3;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>optional string uuid = 8;</code>
     * @return Whether the uuid field is set.
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 8;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 8;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string provisioningCode = 4;</code>
     * @return Whether the provisioningCode field is set.
     */
    boolean hasProvisioningCode();
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @return The provisioningCode.
     */
    java.lang.String getProvisioningCode();
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @return The bytes for provisioningCode.
     */
    com.google.protobuf.ByteString
        getProvisioningCodeBytes();

    /**
     * <code>optional string userAgent = 5;</code>
     * @return Whether the userAgent field is set.
     */
    boolean hasUserAgent();
    /**
     * <code>optional string userAgent = 5;</code>
     * @return The userAgent.
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string userAgent = 5;</code>
     * @return The bytes for userAgent.
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    /**
     * <code>optional bytes profileKey = 6;</code>
     * @return Whether the profileKey field is set.
     */
    boolean hasProfileKey();
    /**
     * <code>optional bytes profileKey = 6;</code>
     * @return The profileKey.
     */
    com.google.protobuf.ByteString getProfileKey();

    /**
     * <code>optional bool readReceipts = 7;</code>
     * @return Whether the readReceipts field is set.
     */
    boolean hasReadReceipts();
    /**
     * <code>optional bool readReceipts = 7;</code>
     * @return The readReceipts.
     */
    boolean getReadReceipts();

    /**
     * <code>optional uint32 provisioningVersion = 9;</code>
     * @return Whether the provisioningVersion field is set.
     */
    boolean hasProvisioningVersion();
    /**
     * <code>optional uint32 provisioningVersion = 9;</code>
     * @return The provisioningVersion.
     */
    int getProvisioningVersion();
  }
  /**
   * Protobuf type {@code signalservice.ProvisionMessage}
   */
  public  static final class ProvisionMessage extends
      com.google.protobuf.GeneratedMessageLite<
          ProvisionMessage, ProvisionMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisionMessage)
      ProvisionMessageOrBuilder {
    private ProvisionMessage() {
      identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
      identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
      number_ = "";
      uuid_ = "";
      provisioningCode_ = "";
      userAgent_ = "";
      profileKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int IDENTITYKEYPUBLIC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString identityKeyPublic_;
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     * @return Whether the identityKeyPublic field is set.
     */
    @java.lang.Override
    public boolean hasIdentityKeyPublic() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     * @return The identityKeyPublic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIdentityKeyPublic() {
      return identityKeyPublic_;
    }
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     * @param value The identityKeyPublic to set.
     */
    private void setIdentityKeyPublic(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      identityKeyPublic_ = value;
    }
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     */
    private void clearIdentityKeyPublic() {
      bitField0_ = (bitField0_ & ~0x00000001);
      identityKeyPublic_ = getDefaultInstance().getIdentityKeyPublic();
    }

    public static final int IDENTITYKEYPRIVATE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString identityKeyPrivate_;
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     * @return Whether the identityKeyPrivate field is set.
     */
    @java.lang.Override
    public boolean hasIdentityKeyPrivate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     * @return The identityKeyPrivate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIdentityKeyPrivate() {
      return identityKeyPrivate_;
    }
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     * @param value The identityKeyPrivate to set.
     */
    private void setIdentityKeyPrivate(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      identityKeyPrivate_ = value;
    }
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    private void clearIdentityKeyPrivate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      identityKeyPrivate_ = getDefaultInstance().getIdentityKeyPrivate();
    }

    public static final int NUMBER_FIELD_NUMBER = 3;
    private java.lang.String number_;
    /**
     * <code>optional string number = 3;</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string number = 3;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      return number_;
    }
    /**
     * <code>optional string number = 3;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(number_);
    }
    /**
     * <code>optional string number = 3;</code>
     * @param value The number to set.
     */
    private void setNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      number_ = value;
    }
    /**
     * <code>optional string number = 3;</code>
     */
    private void clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      number_ = getDefaultInstance().getNumber();
    }
    /**
     * <code>optional string number = 3;</code>
     * @param value The bytes for number to set.
     */
    private void setNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      number_ = value.toStringUtf8();
    }

    public static final int UUID_FIELD_NUMBER = 8;
    private java.lang.String uuid_;
    /**
     * <code>optional string uuid = 8;</code>
     * @return Whether the uuid field is set.
     */
    @java.lang.Override
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string uuid = 8;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      return uuid_;
    }
    /**
     * <code>optional string uuid = 8;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(uuid_);
    }
    /**
     * <code>optional string uuid = 8;</code>
     * @param value The uuid to set.
     */
    private void setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      uuid_ = value;
    }
    /**
     * <code>optional string uuid = 8;</code>
     */
    private void clearUuid() {
      bitField0_ = (bitField0_ & ~0x00000008);
      uuid_ = getDefaultInstance().getUuid();
    }
    /**
     * <code>optional string uuid = 8;</code>
     * @param value The bytes for uuid to set.
     */
    private void setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      uuid_ = value.toStringUtf8();
    }

    public static final int PROVISIONINGCODE_FIELD_NUMBER = 4;
    private java.lang.String provisioningCode_;
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @return Whether the provisioningCode field is set.
     */
    @java.lang.Override
    public boolean hasProvisioningCode() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @return The provisioningCode.
     */
    @java.lang.Override
    public java.lang.String getProvisioningCode() {
      return provisioningCode_;
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @return The bytes for provisioningCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProvisioningCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(provisioningCode_);
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @param value The provisioningCode to set.
     */
    private void setProvisioningCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      provisioningCode_ = value;
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    private void clearProvisioningCode() {
      bitField0_ = (bitField0_ & ~0x00000010);
      provisioningCode_ = getDefaultInstance().getProvisioningCode();
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     * @param value The bytes for provisioningCode to set.
     */
    private void setProvisioningCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      provisioningCode_ = value.toStringUtf8();
    }

    public static final int USERAGENT_FIELD_NUMBER = 5;
    private java.lang.String userAgent_;
    /**
     * <code>optional string userAgent = 5;</code>
     * @return Whether the userAgent field is set.
     */
    @java.lang.Override
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string userAgent = 5;</code>
     * @return The userAgent.
     */
    @java.lang.Override
    public java.lang.String getUserAgent() {
      return userAgent_;
    }
    /**
     * <code>optional string userAgent = 5;</code>
     * @return The bytes for userAgent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userAgent_);
    }
    /**
     * <code>optional string userAgent = 5;</code>
     * @param value The userAgent to set.
     */
    private void setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userAgent_ = value;
    }
    /**
     * <code>optional string userAgent = 5;</code>
     */
    private void clearUserAgent() {
      bitField0_ = (bitField0_ & ~0x00000020);
      userAgent_ = getDefaultInstance().getUserAgent();
    }
    /**
     * <code>optional string userAgent = 5;</code>
     * @param value The bytes for userAgent to set.
     */
    private void setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userAgent_ = value.toStringUtf8();
    }

    public static final int PROFILEKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString profileKey_;
    /**
     * <code>optional bytes profileKey = 6;</code>
     * @return Whether the profileKey field is set.
     */
    @java.lang.Override
    public boolean hasProfileKey() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bytes profileKey = 6;</code>
     * @return The profileKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProfileKey() {
      return profileKey_;
    }
    /**
     * <code>optional bytes profileKey = 6;</code>
     * @param value The profileKey to set.
     */
    private void setProfileKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      profileKey_ = value;
    }
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    private void clearProfileKey() {
      bitField0_ = (bitField0_ & ~0x00000040);
      profileKey_ = getDefaultInstance().getProfileKey();
    }

    public static final int READRECEIPTS_FIELD_NUMBER = 7;
    private boolean readReceipts_;
    /**
     * <code>optional bool readReceipts = 7;</code>
     * @return Whether the readReceipts field is set.
     */
    @java.lang.Override
    public boolean hasReadReceipts() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional bool readReceipts = 7;</code>
     * @return The readReceipts.
     */
    @java.lang.Override
    public boolean getReadReceipts() {
      return readReceipts_;
    }
    /**
     * <code>optional bool readReceipts = 7;</code>
     * @param value The readReceipts to set.
     */
    private void setReadReceipts(boolean value) {
      bitField0_ |= 0x00000080;
      readReceipts_ = value;
    }
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    private void clearReadReceipts() {
      bitField0_ = (bitField0_ & ~0x00000080);
      readReceipts_ = false;
    }

    public static final int PROVISIONINGVERSION_FIELD_NUMBER = 9;
    private int provisioningVersion_;
    /**
     * <code>optional uint32 provisioningVersion = 9;</code>
     * @return Whether the provisioningVersion field is set.
     */
    @java.lang.Override
    public boolean hasProvisioningVersion() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint32 provisioningVersion = 9;</code>
     * @return The provisioningVersion.
     */
    @java.lang.Override
    public int getProvisioningVersion() {
      return provisioningVersion_;
    }
    /**
     * <code>optional uint32 provisioningVersion = 9;</code>
     * @param value The provisioningVersion to set.
     */
    private void setProvisioningVersion(int value) {
      bitField0_ |= 0x00000100;
      provisioningVersion_ = value;
    }
    /**
     * <code>optional uint32 provisioningVersion = 9;</code>
     */
    private void clearProvisioningVersion() {
      bitField0_ = (bitField0_ & ~0x00000100);
      provisioningVersion_ = 0;
    }

    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code signalservice.ProvisionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisionMessage)
        su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessageOrBuilder {
      // Construct using su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       * @return Whether the identityKeyPublic field is set.
       */
      @java.lang.Override
      public boolean hasIdentityKeyPublic() {
        return instance.hasIdentityKeyPublic();
      }
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       * @return The identityKeyPublic.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIdentityKeyPublic() {
        return instance.getIdentityKeyPublic();
      }
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       * @param value The identityKeyPublic to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityKeyPublic(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdentityKeyPublic(value);
        return this;
      }
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentityKeyPublic() {
        copyOnWrite();
        instance.clearIdentityKeyPublic();
        return this;
      }

      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       * @return Whether the identityKeyPrivate field is set.
       */
      @java.lang.Override
      public boolean hasIdentityKeyPrivate() {
        return instance.hasIdentityKeyPrivate();
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       * @return The identityKeyPrivate.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIdentityKeyPrivate() {
        return instance.getIdentityKeyPrivate();
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       * @param value The identityKeyPrivate to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityKeyPrivate(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdentityKeyPrivate(value);
        return this;
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentityKeyPrivate() {
        copyOnWrite();
        instance.clearIdentityKeyPrivate();
        return this;
      }

      /**
       * <code>optional string number = 3;</code>
       * @return Whether the number field is set.
       */
      @java.lang.Override
      public boolean hasNumber() {
        return instance.hasNumber();
      }
      /**
       * <code>optional string number = 3;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        return instance.getNumber();
      }
      /**
       * <code>optional string number = 3;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        return instance.getNumberBytes();
      }
      /**
       * <code>optional string number = 3;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setNumber(value);
        return this;
      }
      /**
       * <code>optional string number = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        copyOnWrite();
        instance.clearNumber();
        return this;
      }
      /**
       * <code>optional string number = 3;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNumberBytes(value);
        return this;
      }

      /**
       * <code>optional string uuid = 8;</code>
       * @return Whether the uuid field is set.
       */
      @java.lang.Override
      public boolean hasUuid() {
        return instance.hasUuid();
      }
      /**
       * <code>optional string uuid = 8;</code>
       * @return The uuid.
       */
      @java.lang.Override
      public java.lang.String getUuid() {
        return instance.getUuid();
      }
      /**
       * <code>optional string uuid = 8;</code>
       * @return The bytes for uuid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUuidBytes() {
        return instance.getUuidBytes();
      }
      /**
       * <code>optional string uuid = 8;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        copyOnWrite();
        instance.setUuid(value);
        return this;
      }
      /**
       * <code>optional string uuid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        copyOnWrite();
        instance.clearUuid();
        return this;
      }
      /**
       * <code>optional string uuid = 8;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUuidBytes(value);
        return this;
      }

      /**
       * <code>optional string provisioningCode = 4;</code>
       * @return Whether the provisioningCode field is set.
       */
      @java.lang.Override
      public boolean hasProvisioningCode() {
        return instance.hasProvisioningCode();
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       * @return The provisioningCode.
       */
      @java.lang.Override
      public java.lang.String getProvisioningCode() {
        return instance.getProvisioningCode();
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       * @return The bytes for provisioningCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProvisioningCodeBytes() {
        return instance.getProvisioningCodeBytes();
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       * @param value The provisioningCode to set.
       * @return This builder for chaining.
       */
      public Builder setProvisioningCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setProvisioningCode(value);
        return this;
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProvisioningCode() {
        copyOnWrite();
        instance.clearProvisioningCode();
        return this;
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       * @param value The bytes for provisioningCode to set.
       * @return This builder for chaining.
       */
      public Builder setProvisioningCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProvisioningCodeBytes(value);
        return this;
      }

      /**
       * <code>optional string userAgent = 5;</code>
       * @return Whether the userAgent field is set.
       */
      @java.lang.Override
      public boolean hasUserAgent() {
        return instance.hasUserAgent();
      }
      /**
       * <code>optional string userAgent = 5;</code>
       * @return The userAgent.
       */
      @java.lang.Override
      public java.lang.String getUserAgent() {
        return instance.getUserAgent();
      }
      /**
       * <code>optional string userAgent = 5;</code>
       * @return The bytes for userAgent.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        return instance.getUserAgentBytes();
      }
      /**
       * <code>optional string userAgent = 5;</code>
       * @param value The userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgent(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserAgent(value);
        return this;
      }
      /**
       * <code>optional string userAgent = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserAgent() {
        copyOnWrite();
        instance.clearUserAgent();
        return this;
      }
      /**
       * <code>optional string userAgent = 5;</code>
       * @param value The bytes for userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserAgentBytes(value);
        return this;
      }

      /**
       * <code>optional bytes profileKey = 6;</code>
       * @return Whether the profileKey field is set.
       */
      @java.lang.Override
      public boolean hasProfileKey() {
        return instance.hasProfileKey();
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       * @return The profileKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getProfileKey() {
        return instance.getProfileKey();
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       * @param value The profileKey to set.
       * @return This builder for chaining.
       */
      public Builder setProfileKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProfileKey(value);
        return this;
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearProfileKey() {
        copyOnWrite();
        instance.clearProfileKey();
        return this;
      }

      /**
       * <code>optional bool readReceipts = 7;</code>
       * @return Whether the readReceipts field is set.
       */
      @java.lang.Override
      public boolean hasReadReceipts() {
        return instance.hasReadReceipts();
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       * @return The readReceipts.
       */
      @java.lang.Override
      public boolean getReadReceipts() {
        return instance.getReadReceipts();
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       * @param value The readReceipts to set.
       * @return This builder for chaining.
       */
      public Builder setReadReceipts(boolean value) {
        copyOnWrite();
        instance.setReadReceipts(value);
        return this;
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearReadReceipts() {
        copyOnWrite();
        instance.clearReadReceipts();
        return this;
      }

      /**
       * <code>optional uint32 provisioningVersion = 9;</code>
       * @return Whether the provisioningVersion field is set.
       */
      @java.lang.Override
      public boolean hasProvisioningVersion() {
        return instance.hasProvisioningVersion();
      }
      /**
       * <code>optional uint32 provisioningVersion = 9;</code>
       * @return The provisioningVersion.
       */
      @java.lang.Override
      public int getProvisioningVersion() {
        return instance.getProvisioningVersion();
      }
      /**
       * <code>optional uint32 provisioningVersion = 9;</code>
       * @param value The provisioningVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProvisioningVersion(int value) {
        copyOnWrite();
        instance.setProvisioningVersion(value);
        return this;
      }
      /**
       * <code>optional uint32 provisioningVersion = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearProvisioningVersion() {
        copyOnWrite();
        instance.clearProvisioningVersion();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signalservice.ProvisionMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "identityKeyPublic_",
              "identityKeyPrivate_",
              "number_",
              "provisioningCode_",
              "userAgent_",
              "profileKey_",
              "readReceipts_",
              "uuid_",
              "provisioningVersion_",
            };
            java.lang.String info =
                "\u0001\t\u0000\u0001\u0001\t\t\u0000\u0000\u0000\u0001\n\u0000\u0002\n\u0001\u0003" +
                "\b\u0002\u0004\b\u0004\u0005\b\u0005\u0006\n\u0006\u0007\u0007\u0007\b\b\u0003\t" +
                "\u000b\b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage> parser = PARSER;
          if (parser == null) {
            synchronized (su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:signalservice.ProvisionMessage)
    private static final su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage DEFAULT_INSTANCE;
    static {
      ProvisionMessage defaultInstance = new ProvisionMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ProvisionMessage.class, defaultInstance);
    }

    public static su.sres.signalservice.internal.push.ProvisioningProtos.ProvisionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ProvisionMessage> PARSER;

    public static com.google.protobuf.Parser<ProvisionMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
